[workspace]
resolver = "3"
members = [ "crates/ast", "crates/checker", "crates/common", "crates/js", "crates/lexer", "crates/parser", "crates/pipeline", "crates/resolver", "crates/tcast","crates/wrc"]
