expression = term ;
term = factor { ( "+" | "-" ) factor } ;
factor = unary { ( "* | "/" ) unary } ;
unary = ( "!" | "-" ) fn_call | fn_call ;
fn_call = member_access "(" [ expression ] { "," expression } ")" | member_access ;
member_access = primary { "." IDENTIFIER } ;
primary = IDENTIFIER | NUMBER | grouping | block | "true" | "false" ;
grouping = "(" expression ")" ;
block = "{" { statement } [ expression ] "}" ;
