program = { statement } ;

statement = expr_stmt | declaration_stmt ;

expr_stmt = expression ";" ;

declaration_stmt = fn_declaration ;

fn_declaration = "fn" IDENTIFIER "(" fn_params ")" "=" expression ;
fn_params = [ IDENTIFIER ":" TYPE ] { "," IDENTIFIER ":" TYPE } ;
